-- Add last-sync to all tables 
ALTER TABLE users
ADD COLUMN last_sync TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();

ALTER TABLE business
ADD COLUMN last_sync TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();

ALTER TABLE products
ADD COLUMN last_sync TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();

ALTER TABLE inventory
ADD COLUMN last_sync TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();

ALTER TABLE inventory_changes
ADD COLUMN last_sync TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();

ALTER TABLE sales
ADD COLUMN last_sync TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();

ALTER TABLE sales_items
ADD COLUMN last_sync TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();

ALTER TABLE sales_payments
ADD COLUMN last_sync TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now();
